name: build
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Gradle compile
      run: ./gradlew compileJava

    - name: Gradle test
      run: ./gradlew test
