name: merge
on: 
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Gradle check
      run: ./gradlew check

    - name: Gradle build
      run: ./gradlew build --scan -s

    - name: Gradle test
      run: ./gradlew test

    - name: Gradle code coverage
      run: ./gradlew codeCoverageReport

    - name: Gradle xml report
      run: ./gradlew jacocoTestReport

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./build/reports/jacoco/test/
        env_vars: OS
        fail_ci_if_error: true
        files: ./build/reports/jacoco/report.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
